language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3
matrix:
  exclude:
    - python: 2.7
      env: PLONE=4.1
    - python: 2.6
      env: PLONE=4.2
    - python: 2.6
      env: PLONE=4.3
before_install:
  - pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
  - sudo apt-get install -qq libxml2-dev libxslt-dev
install:
  - python bootstrap.py -c travis-$PLONE.cfg
  - bin/buildout -t 3 -c travis-$PLONE.cfg -q
script: bin/test